apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: theme-park-api
  namespace: openshift-gitops
spec:
  project: theme-park-api
  destination:
    name: in-cluster
    namespace: theme-park-api
  source:
    repoURL: 'https://git.taco.moe/openshift/openshift-url-rewriting-example.git'
    path: '.'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
