apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/description: "Example application continously deployed with OpenShift GitOps (Argo)"
    openshift.io/display-name: "Theme Park API"
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
    kubernetes.io/metadata.name: theme-park-api
    # openshift-pipelines.tekton.dev/namespace-reconcile-version: v1.6.2
  name: theme-park-api
spec:
  finalizers:
  - kubernetes
